### PR TITLE
Expose more APIs for tasks

### PR DESCRIPTION
**Pull request by arunkannawadi**

### CODE REVIEW

**Comment by arunkannawadi** [comment]
@beckermr - looks like `mamba install` on this package is broken (?)

**Comment by esheldon** [comment]
Running the same on my local machine works ok.  It may be something about the container environment

**Comment by arunkannawadi** [comment]
Thanks Erin, good to know that this passes locally.  the testing only partial on GitHub Actions without the special dependencies?

**Comment by esheldon** [comment]
My recent pushes above have fixed the issue, it now passes CI

**Comment by esheldon** [comment]
Is this ready for review?

**Comment by arunkannawadi** [comment]
Yes, it is. But I'd like to merge this along with the other PR in descwl-coadd-task after some testing.

**Comment by arunkannawadi** [comment]
The tasks in `descwl-coadd-task` repo needs these changes as well.

**Review by beckermr — COMMENTED** [review]
LGTM from me but @esheldon should sign off.

**Comment by arunkannawadi** [comment]
Thanks Erin & Matt!

**Pull request merged**
