### PR TITLE
initial commits, including test skeleton

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Comment by esheldon** [comment]
@beckermr you said I should ask you about using the stack in travis

**Comment by beckermr** [comment]
Yup. Can you add me with full access rights to this repo?

**Comment by esheldon** [comment]
done now, sorry about that, I meant to do so initially.

**Comment by beckermr** [comment]
Alright, let's wait on this CI job. I setup travis to cache the stackvana install. If this works, then it should save us a ton of CI time since pulling down stackvana and installing it takes a ton of tim.

**Comment by beckermr** [comment]
The caching itself might be slow OFC, but I am hoping this is a better solution. We shall see!

**Comment by esheldon** [comment]
looks like retrieving the cache stalled (took more than 20 minutes)

**Comment by beckermr** [comment]
Ahhh crap. I guess we should try without.

**Comment by beckermr** [comment]
Alright. The failure is flake8. I guess we should rebuild the env each time.

**Pull request merged**
