### PR TITLE
Log individual flag in verify_warp

### PR DESCRIPTION
**Pull request by zhouconghao**
Currently, `verify_warp` always logs the first flag name with the total number of flagged pixels, which might be confusing if there are more than one flag. After this PR the code should correctly log the right flag name and right number of flagged pixels joined by and.

Should I write a test for this, given it's a bug in the log message? Thanks!

### CODE REVIEW

**Comment by zhouconghao** [comment]
The failing test is addressed in https://github.com/LSSTDESC/descwl_coadd/pull/86

**Comment by esheldon** [comment]
Rather than using `print` should we add these to the exception string?

**Comment by zhouconghao** [comment]
Thank you, Erin! The size and flag name info is already in the exception string so I just deleted `print`.

**Comment by esheldon** [comment]
looks good to me

**Pull request merged**
